version: '3.3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prompt_share_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: prompt_password
      POSTGRES_DB: prompt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prompt_share"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 