"""add_wallet_address_to_user

Revision ID: 0471dbcd48ef
Revises: b6531d73cd76
Create Date: 2025-04-09 13:40:09.664718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0471dbcd48ef'
down_revision: Union[str, None] = 'b6531d73cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wallet_address')
    # ### end Alembic commands ###
