"""fix_table_dependencies

Revision ID: 190e1ecccf4d
Revises: ddfd2089dbb1
Create Date: 2025-04-08 13:06:15.548455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '190e1ecccf4d'
down_revision = 'ddfd2089dbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SOL payment-related fields to Payment model
    op.add_column('payment', sa.Column('sol_amount', sa.Float(), nullable=True))
    op.add_column('payment', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('blockchain_tx_id', sa.String(), nullable=True))
    
    # Add SOL payment fields to Order model
    op.add_column('order', sa.Column('sol_amount', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('payment_type', sa.String(), server_default='fiat', nullable=False))
    op.add_column('order', sa.Column('notes', sa.Text(), nullable=True))
    
    # Add is_free field to Prompt model if it doesn't exist
    op.add_column('prompt', sa.Column('is_free', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('prompt', sa.Column('sol_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove SOL payment fields from Payment model
    op.drop_column('payment', 'sol_amount')
    op.drop_column('payment', 'wallet_address')
    op.drop_column('payment', 'blockchain_tx_id')
    
    # Remove SOL payment fields from Order model  
    op.drop_column('order', 'sol_amount')
    op.drop_column('order', 'payment_type')
    op.drop_column('order', 'notes')
    
    # Remove fields from Prompt model
    op.drop_column('prompt', 'is_free')
    op.drop_column('prompt', 'sol_price')
    # ### end Alembic commands ###
