"""add_is_active_to_category

Revision ID: 729b9364af21
Revises: 4b137fcc02d0
Create Date: 2025-04-08 10:51:58.537399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729b9364af21'
down_revision = '4b137fcc02d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_active')
    # ### end Alembic commands ###
