"""create_favorite_table

Revision ID: b6531d73cd76
Revises: 
Create Date: 2025-04-09 13:08:16.300597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6531d73cd76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_id'), 'favorite', ['id'], unique=False)
    op.alter_column('order', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'fiat'::character varying"))
    op.drop_constraint('order_payment_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.create_unique_constraint(None, 'payment', ['order_id'])
    op.drop_column('prompt', 'is_free')
    op.drop_column('prompt', 'sol_price')
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SELLER', name='userrole'),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SELLER', name='userrole'),
               nullable=True)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('prompt', sa.Column('sol_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prompt', sa.Column('is_free', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment', type_='unique')
    op.add_column('order', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_payment_id_fkey', 'order', 'payment', ['payment_id'], ['id'])
    op.alter_column('order', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'fiat'::character varying"))
    op.drop_index(op.f('ix_favorite_id'), table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###
