"""add_sol_payment_fields

Revision ID: ddfd2089dbb1
Revises: 729b9364af21
Create Date: 2025-04-08 12:57:55.330079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddfd2089dbb1'
down_revision = '729b9364af21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed all drop table commands to fix dependency issues
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed recreation of tables to avoid schema conflicts
    pass
    # ### end Alembic commands ###
